#need review 
#steps:
#  - name: maven:3.6.3-jdk-8-slim
#    entrypoint: 'mvn'
#    args: ['clean', 'install', '-DskipTests']
 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/[docker-test]:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/[docker-test]:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - '[docker-test]'
   - '--image'
   - 'gcr.io/$PROJECT_ID/[docker-test]:$COMMIT_SHA'
   - '--region'
   - '[europe-west1]'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/$PROJECT_ID/[docker-test]:$COMMIT_SHA'
