#need review 
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/Petclinic-mysql-db', '.']
images: ['gcr.io/$PROJECT_ID/Petclinic-mysql-db']

