#need review 
#steps:
#- name: maven:3.6.3-jdk-8-slim
#  entrypoint: 'mvn'
#  args: ['clean', 'install', '-DskipTests']
  
 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/higginsc2150879/docker-test25189', '--build-arg=JAR_FILE=target/build-artifact']
images: ['gcr.io/higginsc2150879/docker-test25189']
