#need review 
#steps:
#- name: maven:3.6.3-jdk-8-slim
#  entrypoint: 'mvn'
#  args: ['clean', 'install', '-DskipTests']
  
 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'eu.gcr.io/higginsc2150879/appengine/default.20200505t211040', '--build-arg=JAR_FILE=target/build-artifact']
images: ['eu.gcr.io/higginsc2150879/appengine/default.20200505t211040']
